const SUCCESS_OK = 200;
const ERROR_CODE = 400;
const ERROR_AUTH = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_CONFLICT = 409;
const ERROR_SERVER = 500;

module.exports = {
  SUCCESS_OK,
  ERROR_CODE,
  ERROR_AUTH,
  ERROR_FORBIDDEN,
  ERROR_NOT_FOUND,
  ERROR_CONFLICT,
  ERROR_SERVER,
};